/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import herramientas.Validacion;
import dominio.Docente_Auxiliar_Dominio;
import modelado.Docente_Auxiliar;
import base_de_datos.Dao;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class Docente_Edicion extends javax.swing.JDialog {

    String mensaje = "";
    Validacion val = new Validacion();
    ArrayList<Docente_Auxiliar_Dominio> lista;
    static Docente_Auxiliar_Dominio objetoModelG;

    public Docente_Edicion(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public Docente_Edicion(java.awt.Frame parent, boolean modal, Docente_Auxiliar_Dominio objetoModel) {
        super(parent, modal);
        objetoModelG = objetoModel;
        initComponents();
        System.out.println("vamos " + objetoModel.getHora_trabajadas());
        identificacion.setText(objetoModel.getIdentificacion());
        nombre.setText(objetoModel.getNombres());
        correo.setText(objetoModel.getCorreo());
        fono.setText("0" + objetoModel.getFono());
        horario.setText(objetoModel.getHorario_tutorias());
        tipoP.setSelectedItem(objetoModel.getTipo_persona());
        horas.setText("" + objetoModel.getHora_trabajadas());
        Nmaterias.setText(String.valueOf(objetoModel.getNum_materias()));
        objetoModel.setSueldo(Double.parseDouble(horas.getText()));
        sueldo.setText("" + objetoModel.getSueldo());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        identificacion = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        correo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        fono = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        horario = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        horas = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        sueldo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        graba = new javax.swing.JToggleButton();
        Nmaterias = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        tipoP = new javax.swing.JComboBox();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Docente");
        setBounds(new java.awt.Rectangle(250, 150, 0, 0));

        identificacion.setEditable(false);
        identificacion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        identificacion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        identificacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                identificacionKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Identificación");

        nombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                nombreFocusLost(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Nombre");

        correo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Correo");

        fono.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fono.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fonoKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Telefono");

        horario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        horario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                horarioFocusLost(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Horario Tutorias");

        horas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        horas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        horas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                horasKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                horasKeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Horas Trabajadas");

        sueldo.setEditable(false);
        sueldo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sueldo.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Sueldo");

        graba.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        graba.setText("Grabar");
        graba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grabaActionPerformed(evt);
            }
        });

        Nmaterias.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Nmaterias.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Nmaterias.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                NmateriasFocusLost(evt);
            }
        });
        Nmaterias.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                NmateriasKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NmateriasKeyTyped(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Numero Materias");

        jToggleButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jToggleButton2.setText("Eliminar");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        jToggleButton3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jToggleButton3.setText("Salir");
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });

        tipoP.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AUXILIAR", "TITULAR" }));
        tipoP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tipoPMouseClicked(evt);
            }
        });
        tipoP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoPActionPerformed(evt);
            }
        });

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(255, 255, 51));
        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("DOCENTE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(correo, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(identificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(horario, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(horas, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jToggleButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(fono, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(16, 16, 16))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(graba, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Nmaterias, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sueldo, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tipoP, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(237, 237, 237))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipoP, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(identificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(correo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fono, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(horario, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(horas, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(Nmaterias, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(sueldo, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(graba, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void grabaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grabaActionPerformed

        int op = Validacion();
        System.out.println(op);
        if (op != 0) {
            JOptionPane.showMessageDialog(null,  mensaje);
        } else {
            Guardar();
            setVisible(false);
        }
    }//GEN-LAST:event_grabaActionPerformed

    private void horasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_horasKeyTyped
        char car = evt.getKeyChar();
        if (horas.getText().length() >= 6) {
            evt.consume();
        }
        if ((car < '0' || car > '9')) {

            evt.consume();

        }

    }//GEN-LAST:event_horasKeyTyped

    private void identificacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_identificacionKeyTyped
        char car = evt.getKeyChar();
        if (identificacion.getText().length() >= 10) {
            evt.consume();
        }
        if ((car < '0' || car > '9')) {
            evt.consume();
        }
    }//GEN-LAST:event_identificacionKeyTyped

    private void fonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fonoKeyTyped
        char car = evt.getKeyChar();
        if (fono.getText().length() >= 10) {
            evt.consume();
        }
        if ((car < '0' || car > '9')) {
            evt.consume();
        }
    }//GEN-LAST:event_fonoKeyTyped

    private void nombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nombreFocusLost
        // TODO add your handling code here:
        nombre.setText(nombre.getText().toUpperCase());
    }//GEN-LAST:event_nombreFocusLost

    private void horarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_horarioFocusLost
        horario.setText(horario.getText().toUpperCase());
    }//GEN-LAST:event_horarioFocusLost

    private void horasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_horasKeyReleased
        // TODO add your handling code here:
        Calculo(horas.getText());

    }//GEN-LAST:event_horasKeyReleased

    private void NmateriasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NmateriasKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_NmateriasKeyReleased

    private void NmateriasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NmateriasKeyTyped
        char car = evt.getKeyChar();
        if (Nmaterias.getText().length() >= 4) {
            evt.consume();
        }
        if ((car < '0' || car > '9')) {
            evt.consume();
        }
    }//GEN-LAST:event_NmateriasKeyTyped

    private void NmateriasFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NmateriasFocusLost
        // TODO add your handling code here:
        if (Nmaterias.getText() == null || "".equals(Nmaterias.getText())) {
            Nmaterias.setText("0");
        }
    }//GEN-LAST:event_NmateriasFocusLost

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        // TODO add your handling code here:
        int R = JOptionPane.showConfirmDialog(null, "Desea Eliminar los datos?", "Pregunta", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (R == 0) {
            Dao opera = new Dao();
            graba.setEnabled(false);
            opera.borrarElemento("academico", "docente_auxiliar", "identificacion", identificacion.getText());

        }
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jToggleButton3ActionPerformed

    private void tipoPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tipoPMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_tipoPMouseClicked

    private void tipoPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoPActionPerformed
        int op = tipoP.getSelectedIndex();
        if (op == 1) {
            horas.setText("0");
            horas.setEnabled(false);
            Calculo(horas.getText());
        }
        if (op == 0) {
            horas.setText("");
            horas.setEnabled(true);
            sueldo.setText("");
        }
    }//GEN-LAST:event_tipoPActionPerformed

    public void Guardar() {
        if (Validacion() == 0) {
            try {
                String codd = Calculo(horas.getText());

                Docente_Auxiliar_Dominio objeto = new Docente_Auxiliar_Dominio(null,
                        identificacion.getText(),
                        nombre.getText(), correo.getText(),
                        Integer.parseInt(fono.getText()), (String) tipoP.getSelectedItem(),
                        Integer.parseInt(Nmaterias.getText()),
                        horario.getText(),
                        codd, Integer.parseInt(horas.getText()));
                String campos1 = "identificacion,nombres,correo,fono,tipo_persona,"
                        + "num_materias,horario,cod_docente,horas_trabajadas,sueldo";
                String val1 = "'" + objeto.getIdentificacion() + "','" + objeto.getNombres() + "','" + objeto.getCorreo()
                        + "','" + objeto.getFono() + "','" + objeto.getTipo_persona() + "','" + objeto.getNum_materias()
                        + "','" + objeto.getHorario_tutorias() + "','" + objeto.getCod_docente() + "','" + objeto.getHora_trabajadas() + "','" + sueldo.getText() + "'";
                Dao opera = new Dao();

                opera.Editar("academico", campos1, val1, "docente_auxiliar", "identificacion", objeto.getIdentificacion());

            } catch (Exception ex) {
                Logger.getLogger(Docente_Edicion.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {
            JOptionPane.showMessageDialog(null, mensaje);
        }

    }

    public int Validacion() {
        mensaje = "";
        int i = 0, co;
        co = identificacion.getText().length();

        co = nombre.getText().length();
        if (co < 6) {
            mensaje = mensaje+ "\n Nombre Inválido";
            i++;
        }

        co = horario.getText().length();
        if (co < 6) {
            mensaje= mensaje + "\n Horario Inválido";
            i++;
        }

        boolean a = val.Correo(correo.getText());

        if (a == false) {
            mensaje =  mensaje+ "\n Correo Inválido";
            i++;
        }

        co = horas.getText().length();
        if (co < 1) {
             mensaje =  mensaje + "\n Valor de hora Inválido";
            i++;
        }
        co = Nmaterias.getText().length();
        if (co < 1) {
             mensaje =  mensaje + "\n Numero de materias Inválido";
            i++;
        }
        return i;
    }

    //***************************
    public String Calculo(String hora) {
        String codd = "";
        if ("AUXILIAR".equals((String) tipoP.getSelectedItem())) {
            codd = "DA";
        }
        if ("TITULAR".equals((String) tipoP.getSelectedItem())) {
            codd = "DT";
        }
        if (hora == null || "".equals(hora)) {
            hora = "0.00";
        }
        Docente_Auxiliar_Dominio objeto1 = new Docente_Auxiliar_Dominio();
        objeto1.setCod_docente(codd);
        double hora1 = Double.parseDouble(hora);
        objeto1.setSueldo(hora1);
        sueldo.setText(String.valueOf(objeto1.getSueldo()));
        return codd;

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Docente_Auxiliar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Docente_Auxiliar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Docente_Auxiliar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Docente_Auxiliar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Docente_Edicion dialog = new Docente_Edicion(new javax.swing.JFrame(), true, objetoModelG);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Nmaterias;
    private javax.swing.JTextField correo;
    private javax.swing.JTextField fono;
    private javax.swing.JToggleButton graba;
    private javax.swing.JTextField horario;
    private javax.swing.JTextField horas;
    private javax.swing.JTextField identificacion;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField sueldo;
    private javax.swing.JComboBox tipoP;
    // End of variables declaration//GEN-END:variables
}
